
source "dev/vars.sh"

## MARATHON
MARATHON_MASTER=zk://${ZK_CLUSTER_IPS}/mesos
MARATHON_ZK=zk://${ZK_CLUSTER_IPS}/mesos
MARATHON_TASK_LOST_EXPUNGE_GC=150000
MARATHON_TASK_LOST_EXPUNGE_INTERVAL=3600000
MARATHON_TASK_LOST_EXPUNGE_INITIAL_DELAY=300000
MARATHON_TASK_LAUNCH_TIMEOUT=300000
MARATHON_RECONCILIATION_INITIAL_DELAY=15000
MARATHON_RECONCILIATION_INTERVAL=600000
MARATHON_ZK_TIMEOUT=10000
MARATHON_ZK_SESSION_TIMEOUT=10000
MARATHON_ZK_MAX_VERSIONS=25
JAVA_OPTS=-Xms2g
MARATHON_HTTP_CREDENTIALS=marathon:pwd
MARATHON_ACCESS_CONTROL_ALLOW_ORIGIN=http://localhost:4200,http://localhost

function marathon_start(){
  ip=${1}
  id=${RANDOM}
  echo -n "Marathon (${ip}) "
  docker run -d -it --ip ${ip} \
    --restart always \
    --name asgard_marathon_${id} \
    --net ${NETWORK_NAME} \
    --env-file <(
      echo MARATHON_HOSTNAME=${ip}
      echo MESOS_IP=${ip}
      echo LIBPROCESS_IP=${ip}
      echo MARATHON_MASTER=${MARATHON_MASTER}
      echo MARATHON_ZK=${MARATHON_ZK}
      echo MARATHON_TASK_LOST_EXPUNGE_GC=${MARATHON_TASK_LOST_EXPUNGE_GC}
      echo MARATHON_TASK_LOST_EXPUNGE_INTERVAL=${MARATHON_TASK_LOST_EXPUNGE_INTERVAL}
      echo MARATHON_TASK_LOST_EXPUNGE_INITIAL_DELAY=${MARATHON_TASK_LOST_EXPUNGE_INITIAL_DELAY}
      echo MARATHON_TASK_LAUNCH_TIMEOUT=${MARATHON_TASK_LAUNCH_TIMEOUT}
      echo MARATHON_RECONCILIATION_INITIAL_DELAY=${MARATHON_RECONCILIATION_INITIAL_DELAY}
      echo MARATHON_RECONCILIATION_INTERVAL=${MARATHON_RECONCILIATION_INTERVAL}
      echo MARATHON_ZK_TIMEOUT=${MARATHON_ZK_TIMEOUT}
      echo MARATHON_ZK_SESSION_TIMEOUT=${MARATHON_ZK_SESSION_TIMEOUT}
      echo MARATHON_ZK_MAX_VERSIONS=${MARATHON_ZK_MAX_VERSIONS}
      echo JAVA_OPTS=${JAVA_OPTS}
      ) \
        mesosphere/marathon:v1.4.12 --enable_features gpu_resources --mesos_role asgard
}

marathon_start ${MARATHON_IP}
marathon_start "172.18.0.32"
