
source "dev/vars.sh"

## MARATHON
MARATHON_HOSTNAME=${MARATHON_IP}
MESOS_IP=${MARATHON_IP}
LIBPROCESS_IP=${MARATHON_IP}
MARATHON_MASTER=zk://${ZK_CLUSTER_IPS}/mesos
MARATHON_ZK=zk://${ZK_CLUSTER_IPS}/mesos
MARATHON_TASK_LOST_EXPUNGE_GC=150000
MARATHON_TASK_LOST_EXPUNGE_INTERVAL=3600000
MARATHON_TASK_LOST_EXPUNGE_INITIAL_DELAY=300000
MARATHON_TASK_LAUNCH_TIMEOUT=300000
MARATHON_RECONCILIATION_INITIAL_DELAY=15000
MARATHON_RECONCILIATION_INTERVAL=600000
MARATHON_ZK_TIMEOUT=10000
MARATHON_ZK_SESSION_TIMEOUT=10000
MARATHON_ZK_MAX_VERSIONS=25
JAVA_OPTS=-Xms2g
MARATHON_HTTP_CREDENTIALS=marathon:pwd
MARATHON_ACCESS_CONTROL_ALLOW_ORIGIN=http://localhost:4200

echo -n "Marathon (${MARATHON_IP}) "
docker run -d -it --ip ${MARATHON_IP} \
  --name asgard_marathon \
  --net ${NETWORK_NAME} \
  --env-file <(
echo MARATHON_HOSTNAME=${MARATHON_HOSTNAME}
echo MESOS_IP=${MESOS_IP}
echo LIBPROCESS_IP=${LIBPROCESS_IP}
echo MARATHON_MASTER=${MARATHON_MASTER}
echo MARATHON_ZK=${MARATHON_ZK}
echo MARATHON_TASK_LOST_EXPUNGE_GC=${MARATHON_TASK_LOST_EXPUNGE_GC}
echo MARATHON_TASK_LOST_EXPUNGE_INTERVAL=${MARATHON_TASK_LOST_EXPUNGE_INTERVAL}
echo MARATHON_TASK_LOST_EXPUNGE_INITIAL_DELAY=${MARATHON_TASK_LOST_EXPUNGE_INITIAL_DELAY}
echo MARATHON_TASK_LAUNCH_TIMEOUT=${MARATHON_TASK_LAUNCH_TIMEOUT}
echo MARATHON_RECONCILIATION_INITIAL_DELAY=${MARATHON_RECONCILIATION_INITIAL_DELAY}
echo MARATHON_RECONCILIATION_INTERVAL=${MARATHON_RECONCILIATION_INTERVAL}
echo MARATHON_ZK_TIMEOUT=${MARATHON_ZK_TIMEOUT}
echo MARATHON_ZK_SESSION_TIMEOUT=${MARATHON_ZK_SESSION_TIMEOUT}
echo MARATHON_ZK_MAX_VERSIONS=${MARATHON_ZK_MAX_VERSIONS}
echo JAVA_OPTS=${JAVA_OPTS}
#echo #MARATHON_HTTP_CREDENTIALS=${MARATHON_HTTP_CREDENTIALS}
echo MARATHON_ACCESS_CONTROL_ALLOW_ORIGIN=${MARATHON_ACCESS_CONTROL_ALLOW_ORIGIN}
) \
  mesosphere/marathon:v1.3.13 --enable_features gpu_resources --mesos_role asgard


#--default_accepted_resource_roles asgard
